# Generated by Django 5.2.18 on 2026-10-09 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_label', models.CharField(max_length=512)),
                ('origin_lat', models.FloatField()),
                ('origin_lon', models.FloatField()),
                ('destination_label', models.CharField(max_length=512)),
                ('destination_lat', models.FloatField()),
                ('destination_lon', models.FloatField()),
                ('departure_at', models.DateTimeField()),
                ('load_lb', models.FloatField()),
                ('checkpoint_interval_miles', models.PositiveSmallIntegerField(choices=[(10, '10 miles'), (25, '25 miles'), (50, '50 miles')], default=25)),
                ('heatmap', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('summary', models.CharField(blank=True, max_length=256)),
                ('distance_miles', models.FloatField()),
                ('duration_hours', models.FloatField()),
                ('arrival_at', models.DateTimeField()),
                ('geometry', models.JSONField(default=list)),
                ('rank', models.PositiveSmallIntegerField()),
                ('is_recommended', models.BooleanField(default=False)),
                ('average_risk', models.FloatField(default=0.0)),
                ('worst_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe'), ('no_travel', 'No Travel')], default='low', max_length=16)),
                ('no_travel_miles', models.FloatField(default=0.0)),
                ('severe_miles', models.FloatField(default=0.0)),
                ('high_miles', models.FloatField(default=0.0)),
                ('moderate_miles', models.FloatField(default=0.0)),
                ('low_miles', models.FloatField(default=0.0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routing.trip')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('distance_miles', models.FloatField()),
                ('segment_miles', models.FloatField(default=0.0)),
                ('eta', models.DateTimeField()),
                ('weather', models.JSONField(blank=True, default=dict)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe'), ('no_travel', 'No Travel')], max_length=16)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('wind_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe'), ('no_travel', 'No Travel')], max_length=16)),
                ('rain_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe'), ('no_travel', 'No Travel')], max_length=16)),
                ('snow_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe'), ('no_travel', 'No Travel')], max_length=16)),
                ('driver', models.CharField(default='wind', max_length=16)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='routing.route')),
            ],
            options={
                'ordering': ['index'],
                'constraints': [models.UniqueConstraint(fields=('route', 'index'), name='unique_checkpoint_per_route')],
            },
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('trip', 'name'), name='unique_route_name_per_trip'),
        ),
    ]
